### ISSUE TITLE
Not found file.

### ISSUE THREAD

**Issue by Biyu-GitHub** [ucbdrive/3d-vehicle-tracking#2]
Hi:
When I run:
```
cd faster-rcnn.pytorch
bash init.sh
```

it's echo 
```
+ echo 'Please move faster_rcnn_200_14_18895.pth to models/res101/gta_det/'
Please move faster_rcnn_200_14_18895.pth to models/res101/gta_det/
+ echo 'Please move faster_rcnn_300_100_175.pth to models/res101/kitti/'
Please move faster_rcnn_300_100_175.pth to models/res101/kitti/
```
but i don't have these files. where i can find theme?

thank youy !

**Comment by eborboihuc** [comment]
Hi @Biyu-GitHub,

Thanks for the question!

The checkpoint files can be downloaded using 
```bash
cd 3d-tracking/
python loader/download.py checkpoint
```

However, it might not be able to download now since the server is currently down for regular maintenance. I'd encourage you to try it a few days later.


If you have further question, please feel free to open a new issue.

---
As a side note for people looking for the data (image, label, detection results, checkpoint), we do recommend you follow the data preparation [guide](https://github.com/ucbdrive/3d-vehicle-tracking/blob/master/3d-tracking/README.md#data-preparation) to download all the data you need.

**Comment by Biyu-GitHub** [comment]
Thank you very much !
