### ISSUE TITLE
Using kitti dataset

### ISSUE THREAD

**Issue by alelopes** [ucbdrive/3d-vehicle-tracking#7]
Hello,

I'm trying to run the faster-rcnn part in Kitti dataset, but I'm not able to do so. I'm doing this so I can reproduce the full pipeline. I did it for GTA one and it worked well.

To run this on Kitti, I downloaded Kitti's left color images of tracking data set and placed it in the correct folder. I can see it running but when using --vis I get no car bounding box. I analyzed the output of the net thresholding it, and I saw that there is no bounding box for 'car' class above 0.5 thres. I tried changing configs in config.py limiting the size of the images and tried other stuff but it didn't work. I'm also using faster_rcnn_300_100_175.pth checkpoint file.

Do you have any clue on where is the mistake?

I was able to do the whole pipeline (from image to tracking) using GTA dataset, even rescaling the input images.

Thanks

**Comment by eborboihuc** [comment]
Hi @alelopes,

As for the detection of KITTI dataset, we recommend using [RRC-Net](https://arxiv.org/abs/1704.05776) to reproduce the detection result on our paper.

Since I cannot tell what's going on from the description, I find the visualization steps might be helpful to check the detection result of KITTI dataset.

1. run `./init.sh` to compile files under `lib/` (you might already done)
2. place `faster_rcnn_300_100_175.pth` under `models/res101/kitti/` (might be done as well)
3. run scripts below 

```bash
#!/usr/bin/env bash

GPU_ID=0
PHASE="train" # "test", "train"
DATASET="kitti"
NET="res101"
BATCH_SIZE=1
WORKER_NUMBER=1
SESSION=300
TEST_EPOCH=100
TEST_CHECKPOINT=175

CUDA_VISIBLE_DEVICES=${GPU_ID} python test_net.py \
    --dataset ${DATASET} \
    --net ${NET} \
    --checksession ${SESSION} \
    --checkepoch ${TEST_EPOCH} \
    --checkpoint ${TEST_CHECKPOINT} \
    --anno ${PHASE} \
    --cuda \
    --vis

echo
echo $(whoami)" : "${SESSION}_${TEST_EPOCH}_${TEST_CHECKPOINT}" Finish!"
echo "Done!!"
```

If you are still not able to reproduce it, please check the output log of `test_net.py`.

Please feel free to re-open this issue.

Best!

**Comment by pravn** [comment]
I might be missing something, but where can I download the faster rcnn checkpoint file faster_rcnn_300_100_175.pth?

The script in init.sh seems to download this (resnet101).
wget https://s3.amazonaws.com/pytorch/models/resnet101-5d3b4d8f.pth

**Comment by pravn** [comment]
Figured this out. Now that the server seems to be back on, all the data and checkpoints are available.
