### ISSUE TITLE
GTA 3d data download 

### ISSUE THREAD

**Issue by Kunika21** [ucbdrive/3d-vehicle-tracking#8]
Hi! I am unable to download the gta 3d images. Server is taking too long to respond. Is there any other link to download it?

**Comment by eborboihuc** [comment]
Hi @Kunika21,

It could be temporal maintenance of our server. I have tested downloading from outside of our server, and it works fine from my end. I'm afraid that we have no plan to put the data on another platform due to the large file size. Perhaps you may give it a try to download again?

If you still cannot download them successfully, please re-open this issue.

Best!

**Comment by Kunika21** [comment]
Hi! 
It is still not resolved. I request you to look into the matter @eborboihuc

**Comment by eborboihuc** [comment]
Can you provide the way you manage to download the data? 
What error message you got? Can you ping the server from your end? Where were you connect from (like your IP)? Do you have a firewall or a proxy that might block the connection?

I would like to help you, but we cannot go into this issue without any evidence provided. And I can download it from outside of our server, which means the server is on and the connection is built.

Hope you can have that problem fixed!

Best!

**Comment by Kunika21** [comment]
Initially I was trying to download it by running download.py script. It was taking too long to connect the server. So I tried downloading manually. Manually also it is throwing error that site is not reachable.

![image](https://user-images.githubusercontent.com/34136027/65574102-258d2a00-df8a-11e9-9bd9-181b94d5edcd.png)
![image](https://user-images.githubusercontent.com/34136027/65574222-7f8def80-df8a-11e9-90d4-854401ede745.png)

**Comment by eborboihuc** [comment]
Hi @Kunika21,

Thanks for the screenshot. Can you ping the server from your end? Where were you connect from (like your IP)? Do you have a DNS before linking to the server? Do you have a firewall or a proxy that might block the connection? These would be some great direction to find out where the issue is.

From the first image, I think you can connect to the server by the message `128.32.162.150:80... connected`. The error code 304 stands for the file not modified on the server, which indicates those files in your local cache is up to date with the server ones.
Maybe you can have a check over the folder `~/3d-vehicle-tracking/3d-tracking/data/zip/` if you already get the file? If there are no files in the folder, then please try a force refresh to clean the cache.

For the second image, I can access the server via the web UI from my end. I would recommend you to take a look at the setting of proxy or firewall. It is most likely blocked somehow and makes you unable to access the server via web browser. Perhaps using another DNS might help.

Best!

**Comment by Kunika21** [comment]
Hey! Sorry for troubling you. The problem was with my server's firewalls.
Thanks for your time!

**Comment by pravn** [comment]
I have the same issue. 
'''
-2019-09-26 18:10:48--  http://dl.yf.io/bdd-data/3d-vehicle-tracking/3d_tracking_checkpoint.zip
Resolving dl.yf.io (dl.yf.io)... 128.32.162.150
Connecting to dl.yf.io (dl.yf.io)|128.32.162.150|:80... failed: No route to host.
--2019-09-26 18:10:49--  http://dl.yf.io/bdd-data/3d-vehicle-tracking/faster_rcnn_checkpoint.zip
Resolving dl.yf.io (dl.yf.io)... 128.32.162.150
Connecting to dl.yf.io (dl.yf.io)|128.32.162.150|:80... --2019-09-26 18:10:50--  http://dl.yf.io/bdd-data/3d-vehicle-tracking/label/gta_3d_tracking_val_label_0001.zip
Resolving dl.yf.io (dl.yf.io)... 128.32.162.150
Connecting to dl.yf.io (dl.yf.io)|128.32.162.150|:80... ^CTraceback (most recent call last):
  File "loader/download.py", line 84, in <module>
    gen_task(args)
  File "loader/download.py", line 58, in gen_task
    downloading(files, args.n_tasks, overwrite=args.overwrite)
  File "loader/download.py", line 80, in downloading
    p.wait()
'''
